const c=window.EDUSTACK_CONFIG||{};
const db=c.SUPABASE_URL&&!c.SUPABASE_URL.includes('YOUR_PROJECT')
  ? window.supabase.createClient(c.SUPABASE_URL,c.SUPABASE_PUBLISHABLE_KEY||c.SUPABASE_ANON_KEY):null;
let session=null;
const $=id=>document.getElementById(id);
document.querySelectorAll('.nav').forEach(x=>x.onclick=()=>view(x.dataset.v));
function view(v){document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.nav').forEach(x=>x.classList.remove('active'));$(v)?.classList.add('active');document.querySelector(`[data-v="${v}"]`)?.classList.add('active');$('title').textContent={overview:'Platform overview',schools:'Customer schools',onboard:'Onboard a school',architecture:'Architecture'}[v]||v}
function safeError(error){return error?.code==='42501'?'You do not have permission for this action.':error?.code==='23505'?'That value is already in use.':'The request could not be completed. Please try again.'}
async function loadSchools(){const o=$('list');if(!db){o.textContent='Supabase is not configured. See docs/ENVIRONMENT_SETUP.md';return}const {data,error}=await db.from('tenants').select('name,slug,status,subscription_status').order('created_at',{ascending:false});o.textContent=error?safeError(error):(data?.length?data.map(x=>`${x.name} | ${x.slug} | ${x.status}`).join('\n'):'No schools yet')}
async function init(){if(!db){$('auth-status').textContent='Demo configuration only — connect Supabase to sign in.';return}const result=await db.auth.getSession();session=result.data.session;if(!session){$('auth-status').textContent='Sign in with a platform administrator account to manage tenants.';return}$('auth-status').textContent=`Signed in as ${session.user.email}`;loadSchools()}
$('login-form').onsubmit=async e=>{e.preventDefault();if(!db){$('auth-status').textContent='Supabase is not configured.';return}const {error}=await db.auth.signInWithPassword({email:$('login-email').value,password:$('login-password').value});$('auth-status').textContent=error?'Sign-in failed. Check your details.':'Signed in. Loading…';if(!error)init()}
$('form').onsubmit=async e=>{e.preventDefault();const o=$('message');if(!db||!session){o.textContent='A signed-in platform administrator is required.';return}o.textContent='Creating tenant…';const modules=[...document.querySelectorAll('.checks input:checked')].map(x=>x.value);const {data,error}=await db.functions.invoke('create-tenant',{body:{name:$('name').value.trim(),slug:$('slug').value.trim(),motto:$('motto').value.trim()||null,branding:{primary_color:$('primary').value,secondary_color:$('secondary').value},modules}});o.textContent=error?safeError(error):`Tenant ${data.tenant.name} created successfully.`;if(!error)loadSchools()}
init();